CREATE SCHEMA dbquiz;
USE dbquiz;
CREATE TABLE categories (id INT PRIMARY KEY, cat_name VARCHAR(50));
INSERT INTO categories (id, cat_name) VALUES
(1, 'Operating Systems'),
(2, 'Database Management Systems'),
(3, 'Computer Networks'),
(4, 'Data Structures and Algorithms'),
(5, 'Design and Analysis of Algorithms'),
(6, 'C++ Programming'),
(7, 'C Programming'),
(8,'Object-Oriented Programming');



CREATE TABLE questions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    question_text TEXT NOT NULL,
    category_id INT,
    correct_option VARCHAR(250) NOT NULL,
    option1 VARCHAR(250) NOT NULL,
    option2 VARCHAR(250) NOT NULL,
    option3 VARCHAR(250) NOT NULL,
    option4 VARCHAR(250) NOT NULL,
    FOREIGN KEY (category_id) REFERENCES categories(id)
);

INSERT INTO questions (question_text, category_id, correct_option, option1, option2, option3, option4) VALUES
('Which scheduling algorithm is non-preemptive?', 1, 'First-Come-First-Serve', 'First-Come-First-Serve', 'Shortest Job Next', 'Round Robin', 'Priority Scheduling'),
('The time taken by the disk arm to move to the required track is called?', 1, 'Seek Time', 'Seek Time', 'Latency', 'Access Time', 'Transfer Time'),
('Which of the following is not a process state?', 1, 'Deadlock', 'Deadlock', 'Running', 'Blocked', 'Ready'),
('What is the function of a Memory Management Unit (MMU)?', 1, 'Translate logical addresses to physical addresses', 'Translate logical addresses to physical addresses', 'Handle process scheduling', 'Manage I/O devices', 'None of the above'),
('Which of the following is used to prevent busy waiting in semaphores?', 1, 'Blocking', 'Blocking', 'Spinlock', 'Polling', 'Interrupts'),
('A system is in a safe state if:', 1, 'There is a safe sequence for all processes', 'There is a safe sequence for all processes', 'All processes can complete their execution', 'Deadlock will not occur', 'The system will crash'),
('Which algorithm is used for deadlock prevention?', 1, 'Banker’s Algorithm', 'Banker’s Algorithm', 'Round Robin', 'FIFO', 'LRU'),
('What is thrashing in an operating system?', 1, 'Excessive page swapping', 'Excessive page swapping', 'Disk failure', 'Process starvation', 'CPU overload'),
('Which of the following is true about multitasking?', 1, 'It allows multiple processes to run simultaneously', 'It allows multiple processes to run simultaneously', 'It is used to execute a single task faster', 'It increases memory usage significantly', 'It is only used in real-time systems'),
('What is the purpose of the `ps` command in Unix?', 1, 'To display currently running processes', 'To display currently running processes', 'To display the file system', 'To display system memory usage', 'To display the system’s date and time'),
('In which of the following states is the process not allowed to execute any instruction?', 1, 'Blocked', 'Blocked', 'Running', 'Ready', 'Suspended'),
('What is the function of a context switch?', 1, 'To save and load the state of a process', 'To save and load the state of a process', 'To allocate memory to processes', 'To manage file systems', 'To handle I/O requests'),
('Which of the following is a non-preemptive scheduling algorithm?', 1, 'FCFS (First-Come, First-Served)', 'FCFS (First-Come, First-Served)', 'Round Robin', 'Shortest Remaining Time First', 'Multilevel Queue Scheduling'),
('What is a critical section?', 1, 'A section of code that accesses shared resources', 'A section of code that accesses shared resources', 'A section of code that is not important', 'A section of code that has an error', 'A section of code that runs infinitely'),
('What is the main disadvantage of the priority scheduling algorithm?', 1, 'Starvation', 'Starvation', 'Complex implementation', 'Low throughput', 'High CPU usage'),
('Which of the following is true about spooling?', 1, 'It stands for Simultaneous Peripheral Operation Online', 'It stands for Simultaneous Peripheral Operation Online', 'It is used to handle interrupt requests', 'It is a technique for memory management', 'It is only used in Unix systems'),
('Which of the following is not a valid page replacement algorithm?', 1, 'Shortest Job First', 'Shortest Job First', 'Least Recently Used (LRU)', 'First-In-First-Out (FIFO)', 'Optimal Page Replacement'),
('What is the use of a shell in an operating system?', 1, 'It provides a user interface', 'It provides a user interface', 'It manages memory', 'It handles hardware devices', 'It schedules processes'),
('Which of the following is not a type of operating system?', 1, 'Firewall OS', 'Firewall OS', 'Batch OS', 'Time-Sharing OS', 'Distributed OS'),
('In the context of operating systems, what is a fork?', 1, 'A system call to create a new process', 'A system call to create a new process', 'A system call to terminate a process', 'A command to list processes', 'A command to view file permissions');


INSERT INTO questions (question_text, category_id, correct_option, option1, option2, option3, option4) VALUES
('Which of the following is a type of join in SQL?', 2, 'INNER JOIN', 'INNER JOIN', 'OUTER JOIN', 'CROSS JOIN', 'ALL OF THE ABOVE'),
('What is the purpose of the primary key in a database?', 2, 'To uniquely identify a record in a table', 'To uniquely identify a record in a table', 'To establish a relationship between two tables', 'To sort the data in the table', 'To provide a shortcut to access data'),
('Which of the following is used to define a schema in SQL?', 2, 'CREATE SCHEMA', 'CREATE SCHEMA', 'ALTER SCHEMA', 'DROP SCHEMA', 'INSERT INTO SCHEMA'),
('What is a foreign key in a relational database?', 2, 'A field in one table that refers to the primary key in another table', 'A field in one table that refers to the primary key in another table', 'A field in one table that uniquely identifies a row in another table', 'A key used to encrypt data', 'A field used to link two tables'),
('What does ACID stand for in the context of databases?', 2, 'Atomicity, Consistency, Isolation, Durability', 'Atomicity, Consistency, Isolation, Durability', 'Accuracy, Consistency, Integrity, Durability', 'Availability, Consistency, Integrity, Durability', 'Atomicity, Consistency, Isolation, Dependency'),
('Which of the following is not a type of SQL command?', 2, 'COMMIT', 'COMMIT', 'SELECT', 'UPDATE', 'DELETE'),
('What is a trigger in SQL?', 2, 'A stored procedure that runs automatically when certain events occur', 'A stored procedure that runs automatically when certain events occur', 'A command to retrieve data', 'A method of indexing', 'A way to join tables'),
('What is the difference between DELETE and TRUNCATE in SQL?', 2, 'DELETE removes rows one at a time and logs each delete, TRUNCATE removes all rows and does not log individual row deletions', 'DELETE removes rows one at a time and logs each delete, TRUNCATE removes all rows and does not log individual row deletions', 'TRUNCATE can be rolled back, DELETE cannot', 'DELETE is faster than TRUNCATE', 'TRUNCATE is used only on indexed tables'),
('Which of the following is true about normalization in databases?', 2, 'It reduces data redundancy', 'It reduces data redundancy', 'It increases the size of the database', 'It makes the database slower', 'It is not required for relational databases'),
('What is a clustered index?', 2, 'An index that rearranges the physical order of the data in a table', 'An index that rearranges the physical order of the data in a table', 'An index that does not alter the physical order of the data in a table', 'An index that is automatically created on primary keys', 'An index that is used only in non-relational databases'),
('What does the COUNT() function do in SQL?', 2, 'Returns the number of rows in a table', 'Returns the number of rows in a table', 'Returns the sum of a column', 'Returns the average value of a column', 'Returns the number of distinct values in a column'),
('What is the purpose of the SQL GROUP BY clause?', 2, 'To group rows that have the same values in specified columns', 'To group rows that have the same values in specified columns', 'To sort the rows in a particular order', 'To combine multiple tables', 'To delete duplicate rows'),
('What is the difference between CHAR and VARCHAR data types in SQL?', 2, 'CHAR is fixed-length, VARCHAR is variable-length', 'CHAR is fixed-length, VARCHAR is variable-length', 'CHAR can store more data than VARCHAR', 'VARCHAR is faster than CHAR', 'CHAR cannot store numeric data, VARCHAR can'),
('What is a composite key?', 2, 'A key that consists of two or more columns', 'A key that consists of two or more columns', 'A key that combines a primary and foreign key', 'A key that is used in a non-relational database', 'A key that is used to encrypt data'),
('Which SQL clause is used to filter records based on a condition?', 2, 'WHERE', 'WHERE', 'HAVING', 'GROUP BY', 'ORDER BY'),
('What is the difference between an INNER JOIN and an OUTER JOIN?', 2, 'INNER JOIN returns only matching rows, OUTER JOIN returns all rows from one or both tables', 'INNER JOIN returns only matching rows, OUTER JOIN returns all rows from one or both tables', 'OUTER JOIN is faster than INNER JOIN', 'INNER JOIN allows null values, OUTER JOIN does not', 'There is no difference between the two'),
('What is a subquery in SQL?', 2, 'A query nested inside another query', 'A query nested inside another query', 'A query that is executed before the main query', 'A query that returns multiple results', 'A query that updates data in a table'),
('Which SQL function is used to combine the result of two or more SELECT statements?', 2, 'UNION', 'UNION', 'INTERSECT', 'EXCEPT', 'JOIN'),
('What is the difference between UNION and UNION ALL in SQL?', 2, 'UNION removes duplicate rows, UNION ALL includes all rows', 'UNION removes duplicate rows, UNION ALL includes all rows', 'UNION is faster than UNION ALL', 'UNION can only combine two tables, UNION ALL can combine more than two tables', 'There is no difference between the two'),
('What does the term "data integrity" mean in the context of databases?', 2, 'The accuracy and consistency of data stored in a database', 'The accuracy and consistency of data stored in a database', 'The speed of data retrieval in a database', 'The structure of the database schema', 'The ability to recover data after a crash');

INSERT INTO questions (question_text, category_id, correct_option, option1, option2, option3, option4) VALUES
('What does TCP stand for?', 3, 'Transmission Control Protocol', 'Transmission Control Protocol', 'Transport Control Protocol', 'Transfer Communication Protocol', 'Telecom Control Protocol'),
('Which layer of the OSI model is responsible for error detection?', 3, 'Data Link Layer', 'Data Link Layer', 'Transport Layer', 'Network Layer', 'Application Layer'),
('Which of the following is a function of the network layer in the OSI model?', 3, 'Routing', 'Routing', 'Encryption', 'Flow Control', 'Error Detection'),
('What is the primary purpose of the ARP protocol?', 3, 'To map an IP address to a MAC address', 'To map an IP address to a MAC address', 'To map a MAC address to an IP address', 'To resolve DNS queries', 'To establish a connection between two hosts'),
('What is the difference between TCP and UDP?', 3, 'TCP is connection-oriented, UDP is connectionless', 'TCP is connection-oriented, UDP is connectionless', 'UDP is faster than TCP', 'TCP is used for real-time applications, UDP is not', 'There is no difference between the two'),
('Which protocol is used for secure communication over the internet?', 3, 'HTTPS', 'HTTPS', 'HTTP', 'FTP', 'SMTP'),
('What is the function of a router in a network?', 3, 'To route data packets between different networks', 'To route data packets between different networks', 'To connect multiple devices to a single network', 'To transmit data over a single network', 'To secure the network from external threats'),
('What is the purpose of a subnet mask?', 3, 'To define the network and host portions of an IP address', 'To define the network and host portions of an IP address', 'To assign IP addresses to devices on a network', 'To encrypt data transmitted over a network', 'To control network traffic'),
('Which of the following is a wireless communication protocol?', 3, 'Wi-Fi', 'Wi-Fi', 'Ethernet', 'TCP/IP', 'USB'),
('What is the maximum number of IP addresses in a Class C network?', 3, '256', '256', '1024', '65536', '128'),
('Which of the following is a characteristic of IPv6?', 3, '128-bit address', '128-bit address', '32-bit address', '64-bit address', '256-bit address'),
('What is the function of the DNS protocol?', 3, 'To translate domain names to IP addresses', 'To translate domain names to IP addresses', 'To establish a connection between two hosts', 'To encrypt data transmitted over the internet', 'To manage routing tables'),
('Which of the following is a type of network topology?', 3, 'Star', 'Star', 'TCP/IP', 'DNS', 'Router'),
('What does the term "bandwidth" refer to in networking?', 3, 'The maximum rate of data transfer over a network', 'The maximum rate of data transfer over a network', 'The physical distance between two network devices', 'The time it takes for data to travel from one device to another', 'The number of devices connected to a network'),
('Which protocol is used for email transmission?', 3, 'SMTP', 'SMTP', 'HTTP', 'FTP', 'SNMP'),
('What is a firewall?', 3, 'A security device that monitors and controls incoming and outgoing network traffic', 'A security device that monitors and controls incoming and outgoing network traffic', 'A device used to route data between networks', 'A type of virus that attacks network devices', 'A software used to encrypt data'),
('Which of the following is true about network segmentation?', 3, 'It divides a network into smaller, isolated segments to improve security and performance', 'It divides a network into smaller, isolated segments to improve security and performance', 'It is used to combine multiple networks into one', 'It increases the speed of data transfer over a network', 'It is only used in wireless networks'),
('What is the primary purpose of NAT (Network Address Translation)?', 3, 'To allow multiple devices on a private network to share a single public IP address', 'To allow multiple devices on a private network to share a single public IP address', 'To route data between different networks', 'To encrypt data transmitted over a network', 'To assign IP addresses to devices on a network'),
('Which layer of the OSI model is responsible for data compression and encryption?', 3, 'Presentation Layer', 'Presentation Layer', 'Application Layer', 'Session Layer', 'Transport Layer'),
('What is the purpose of the ICMP protocol?', 3, 'To send error messages and operational information', 'To send error messages and operational information', 'To transmit data between devices on a network', 'To establish a connection between two hosts', 'To manage routing tables');

INSERT INTO questions (question_text, category_id, correct_option, option1, option2, option3, option4) VALUES
('Which data structure uses LIFO (Last In First Out) principle?', 4, 'Stack', 'Stack', 'Queue', 'Linked List', 'Tree'),
('What is the time complexity of binary search?', 4, 'O(log n)', 'O(log n)', 'O(n)', 'O(n^2)', 'O(1)'),
('Which data structure is best suited for implementing a priority queue?', 4, 'Heap', 'Heap', 'Array', 'Stack', 'Linked List'),
('Which of the following algorithms is used for sorting?', 4, 'Merge Sort', 'Merge Sort', 'Dijkstra’s Algorithm', 'Kruskal’s Algorithm', 'Floyd-Warshall Algorithm'),
('In a linked list, what is the time complexity to access an element?', 4, 'O(n)', 'O(n)', 'O(1)', 'O(log n)', 'O(n^2)'),
('What is the worst-case time complexity of Quick Sort?', 4, 'O(n^2)', 'O(n^2)', 'O(n log n)', 'O(n)', 'O(log n)'),
('Which of the following data structures is used to implement recursion?', 4, 'Stack', 'Stack', 'Queue', 'Tree', 'Graph'),
('What is a circular queue?', 4, 'A queue in which the last position is connected back to the first position', 'A queue in which the last position is connected back to the first position', 'A queue in which elements are arranged in a circular manner', 'A queue in which elements can be added or removed from both ends', 'A queue in which elements are arranged in a hierarchical manner'),
('Which of the following is not a type of binary tree?', 4, 'Hash Tree', 'Hash Tree', 'AVL Tree', 'Red-Black Tree', 'Splay Tree'),
('What is the space complexity of a depth-first search (DFS)?', 4, 'O(V)', 'O(V)', 'O(E)', 'O(V+E)', 'O(1)'),
('In a binary search tree, which traversal method will give the elements in ascending order?', 4, 'In-order traversal', 'In-order traversal', 'Pre-order traversal', 'Post-order traversal', 'Level-order traversal'),
('What is a hash table?', 4, 'A data structure that maps keys to values using a hash function', 'A data structure that maps keys to values using a hash function', 'A data structure that stores elements in a sorted order', 'A data structure that uses a binary tree for storage', 'A data structure that stores elements in a circular manner'),
('Which of the following is an example of a greedy algorithm?', 4, 'Huffman Coding', 'Huffman Coding', 'Merge Sort', 'Binary Search', 'Dynamic Programming'),
('What is the time complexity of finding the minimum element in a min-heap?', 4, 'O(1)', 'O(1)', 'O(log n)', 'O(n)', 'O(n log n)'),
('In graph theory, what is a spanning tree?', 4, 'A subgraph that includes all vertices and is a tree', 'A subgraph that includes all vertices and is a tree', 'A subgraph that includes all edges and is a tree', 'A graph that contains cycles', 'A graph that contains only one vertex'),
('Which of the following algorithms is used to find the shortest path in a weighted graph?', 4, 'Dijkstra’s Algorithm', 'Dijkstra’s Algorithm', 'Kruskal’s Algorithm', 'Floyd-Warshall Algorithm', 'Prim’s Algorithm'),
('What is a queue?', 4, 'A data structure that follows FIFO (First In First Out) principle', 'A data structure that follows FIFO (First In First Out) principle', 'A data structure that follows LIFO (Last In First Out) principle', 'A data structure used for sorting', 'A data structure used for searching'),
('What is a binary tree?', 4, 'A tree data structure in which each node has at most two children', 'A tree data structure in which each node has at most two children', 'A tree data structure in which each node has at most three children', 'A tree data structure in which each node has at most one child', 'A tree data structure in which each node has an unlimited number of children'),
('What is the time complexity of inserting an element in a binary search tree?', 4, 'O(log n)', 'O(log n)', 'O(n)', 'O(n^2)', 'O(1)'),
('Which of the following is a self-balancing binary search tree?', 4, 'AVL Tree', 'AVL Tree', 'Binary Search Tree', 'Red-Black Tree', 'B-Tree');

INSERT INTO questions (question_text, category_id, correct_option, option1, option2, option3, option4) VALUES
('Which of the following is a divide and conquer algorithm?', 5, 'Merge Sort', 'Merge Sort', 'Bubble Sort', 'Selection Sort', 'Insertion Sort'),
('The Big-O notation is used to express?', 5, 'The upper bound of an algorithm', 'The upper bound of an algorithm', 'The lower bound of an algorithm', 'The average case of an algorithm', 'All of the above'),
('What is dynamic programming?', 5, 'A method for solving complex problems by breaking them down into simpler subproblems', 'A method for solving complex problems by breaking them down into simpler subproblems', 'A method for finding the shortest path in a graph', 'A method for sorting data', 'A method for searching data'),
('Which of the following is a greedy algorithm?', 5, 'Kruskal’s Algorithm', 'Kruskal’s Algorithm', 'Merge Sort', 'Binary Search', 'Breadth-First Search'),
('What is the time complexity of the merge sort algorithm?', 5, 'O(n log n)', 'O(n log n)', 'O(n^2)', 'O(n)', 'O(log n)'),
('In the context of algorithm analysis, what is a heuristic?', 5, 'A rule of thumb that provides a good solution in a reasonable amount of time', 'A rule of thumb that provides a good solution in a reasonable amount of time', 'A method for finding the optimal solution to a problem', 'A method for solving NP-complete problems', 'A method for sorting data'),
('Which of the following is an NP-complete problem?', 5, 'Travelling Salesman Problem', 'Travelling Salesman Problem', 'Binary Search', 'Bubble Sort', 'Insertion Sort'),
('What is a recurrence relation?', 5, 'An equation that recursively defines a sequence of values', 'An equation that recursively defines a sequence of values', 'A method for solving systems of linear equations', 'A method for analyzing sorting algorithms', 'A method for finding the shortest path in a graph'),
('Which algorithm is used to solve the knapsack problem?', 5, 'Dynamic Programming', 'Dynamic Programming', 'Greedy Algorithm', 'Divide and Conquer', 'Backtracking'),
('What is the time complexity of the quicksort algorithm in the worst case?', 5, 'O(n^2)', 'O(n^2)', 'O(n log n)', 'O(n)', 'O(log n)'),
('Which of the following problems can be solved using the backtracking approach?', 5, 'N-Queens Problem', 'N-Queens Problem', 'Binary Search', 'Bubble Sort', 'Breadth-First Search'),
('What is the branch and bound technique?', 5, 'A method for solving combinatorial optimization problems', 'A method for solving combinatorial optimization problems', 'A method for sorting data', 'A method for searching data', 'A method for solving linear equations'),
('What is the purpose of the Huffman coding algorithm?', 5, 'To compress data by reducing the number of bits required to represent each symbol', 'To compress data by reducing the number of bits required to represent each symbol', 'To sort data in ascending order', 'To find the shortest path in a graph', 'To search for a specific element in a list'),
('Which of the following is true about the Bellman-Ford algorithm?', 5, 'It can handle graphs with negative weight edges', 'It can handle graphs with negative weight edges', 'It is faster than Dijkstra’s algorithm', 'It can only be used on undirected graphs', 'It cannot be used on weighted graphs'),
('What is the time complexity of the Floyd-Warshall algorithm?', 5, 'O(n^3)', 'O(n^3)', 'O(n^2)', 'O(n log n)', 'O(n)'),
('What is a greedy algorithm?', 5, 'An algorithm that always makes the locally optimal choice at each step', 'An algorithm that always makes the locally optimal choice at each step', 'An algorithm that uses dynamic programming', 'An algorithm that divides the problem into smaller subproblems', 'An algorithm that uses backtracking'),
('Which of the following is true about the travelling salesman problem?', 5, 'It is NP-hard', 'It is NP-hard', 'It can be solved in polynomial time', 'It is a sorting problem', 'It is a searching problem'),
('What is the purpose of the dynamic programming technique?', 5, 'To solve complex problems by breaking them down into simpler subproblems', 'To solve complex problems by breaking them down into simpler subproblems', 'To find the shortest path in a graph', 'To sort data in ascending order', 'To search for a specific element in a list'),
('Which of the following is a characteristic of a divide and conquer algorithm?', 5, 'It divides the problem into smaller subproblems, solves them, and combines their results', 'It divides the problem into smaller subproblems, solves them, and combines their results', 'It always makes the locally optimal choice', 'It uses dynamic programming to solve problems', 'It solves problems by searching for a specific element in a list'),
('Which of the following is true about NP-complete problems?', 5, 'If one NP-complete problem can be solved in polynomial time, then all NP-complete problems can be solved in polynomial time', 'If one NP-complete problem can be solved in polynomial time, then all NP-complete problems can be solved in polynomial time', 'NP-complete problems can be solved in linear time', 'NP-complete problems can be solved using greedy algorithms', 'NP-complete problems are unsolvable');


INSERT INTO questions (question_text, category_id, correct_option, option1, option2, option3, option4) VALUES
('What is the purpose of a constructor in C++?', 6, 'To initialize objects of a class', 'To initialize objects of a class', 'To allocate memory', 'To delete objects of a class', 'To create a new class'),
('Which of the following is a feature of object-oriented programming in C++?', 6, 'Encapsulation', 'Encapsulation', 'Recursion', 'Pointers', 'Macros'),
('What is the output of the following C++ code? \nint main() { int x = 5; std::cout << x++; return 0; }', 6, '5', '5', '6', 'Error', 'Undefined'),
('Which of the following operators is used to allocate memory dynamically in C++?', 6, 'new', 'new', 'malloc', 'alloc', 'create'),
('What is the difference between a struct and a class in C++?', 6, 'By default, members of a struct are public, while members of a class are private', 'By default, members of a struct are public, while members of a class are private', 'There is no difference', 'A struct cannot have member functions', 'A class cannot have data members'),
('Which of the following is not a type of inheritance in C++?', 6, 'Triple Inheritance', 'Triple Inheritance', 'Single Inheritance', 'Multiple Inheritance', 'Hierarchical Inheritance'),
('What is the purpose of the "this" pointer in C++?', 6, 'To point to the current object of a class', 'To point to the current object of a class', 'To point to the base class', 'To point to the next object in memory', 'To point to the first object of a class'),
('Which of the following is a correct syntax for defining a namespace in C++?', 6, 'namespace name { }', 'namespace name { }', 'define namespace name { }', 'namespace name [ ]', 'class namespace name { }'),
('What is polymorphism in C++?', 6, 'The ability of a function or object to take many forms', 'The ability of a function or object to take many forms', 'The ability of a function to call itself', 'The ability of a class to have multiple constructors', 'The ability of a pointer to point to multiple objects'),
('Which of the following is an example of compile-time polymorphism in C++?', 6, 'Function overloading', 'Function overloading', 'Virtual functions', 'Inheritance', 'Operator overloading'),
('What is the use of the "virtual" keyword in C++?', 6, 'To allow a function to be overridden in a derived class', 'To allow a function to be overridden in a derived class', 'To allocate memory dynamically', 'To create an abstract class', 'To create a pointer to an object'),
('Which of the following is true about the "delete" operator in C++?', 6, 'It deallocates memory allocated by the "new" operator', 'It deallocates memory allocated by the "new" operator', 'It deletes a file', 'It removes an element from an array', 'It removes a pointer from a list'),
('What is an abstract class in C++?', 6, 'A class that cannot be instantiated and is meant to be inherited', 'A class that cannot be instantiated and is meant to be inherited', 'A class that does not have any data members', 'A class that is used to create objects', 'A class that can be instantiated only once'),
('Which of the following is true about a destructor in C++?', 6, 'It is called when an object is destroyed', 'It is called when an object is destroyed', 'It must return an integer value', 'It must be called explicitly', 'It is used to allocate memory'),
('What is the purpose of the "const" keyword in C++?', 6, 'To make a variable or function parameter constant', 'To make a variable or function parameter constant', 'To define a constant value', 'To create a constant pointer', 'To prevent a function from being overridden'),
('Which of the following is true about operator overloading in C++?', 6, 'It allows operators to be redefined for user-defined types', 'It allows operators to be redefined for user-defined types', 'It can only be used with built-in types', 'It cannot be used with pointers', 'It must be done at runtime'),
('What is the difference between a reference and a pointer in C++?', 6, 'A reference is an alias for another variable, while a pointer stores the address of a variable', 'A reference is an alias for another variable, while a pointer stores the address of a variable', 'There is no difference', 'A pointer can point to a function, but a reference cannot', 'A reference must be initialized, while a pointer can be null'),
('What is the purpose of the "friend" keyword in C++?', 6, 'To allow a non-member function or another class to access private or protected members of a class', 'To allow a non-member function or another class to access private or protected members of a class', 'To create a friend class', 'To allow a class to access members of another class', 'To declare a function inside a class'),
('Which of the following is true about the "const" member function in C++?', 6, 'It cannot modify any member variables of the class', 'It cannot modify any member variables of the class', 'It must return a constant value', 'It cannot be called from outside the class', 'It must be defined inside the class'),
('What is the purpose of the "static" keyword in C++?', 6, 'To declare a variable or function that is shared by all objects of a class', 'To declare a variable or function that is shared by all objects of a class', 'To create a static class', 'To prevent a class from being inherited', 'To declare a constant value');

INSERT INTO questions (question_text, category_id, correct_option, option1, option2, option3, option4) VALUES
('Which of the following is not a valid storage class in C?', 7, 'mutable', 'auto', 'static', 'register', 'mutable'),
('What is the purpose of the "main()" function in a C program?', 7, 'It is the entry point of the program', 'It is the entry point of the program', 'It is used to initialize variables', 'It is used to define global variables', 'It is used to return the value of a program'),
('Which of the following is a valid declaration of a pointer in C?', 7, 'int *ptr;', 'int *ptr;', 'int ptr*;', 'int * ptr;', 'int *-ptr;'),
('Which of the following operators is used to allocate memory dynamically in C?', 7, 'malloc', 'malloc', 'new', 'alloc', 'calloc'),
('What is the output of the following C code?\n#include <stdio.h>\nint main() { int a = 10, b = 20; printf("%d", a++ + b); return 0; }', 7, '30', '30', '31', '29', 'Error'),
('Which of the following is not a valid loop in C?', 7, 'repeat-until', 'repeat-until', 'for', 'while', 'do-while'),
('Which of the following is true about the "sizeof" operator in C?', 7, 'It returns the size of a variable or data type in bytes', 'It returns the size of a variable or data type in bytes', 'It returns the length of a string', 'It returns the number of elements in an array', 'It returns the size of a file'),
('What is the difference between a structure and a union in C?', 7, 'In a structure, all members have their own memory, while in a union, all members share the same memory', 'In a structure, all members have their own memory, while in a union, all members share the same memory', 'There is no difference', 'A structure cannot have member functions, while a union can', 'A union cannot be passed as a function argument, while a structure can'),
('Which of the following is true about the "typedef" keyword in C?', 7, 'It is used to create an alias for a data type', 'It is used to create an alias for a data type', 'It is used to define a new data type', 'It is used to declare a variable', 'It is used to define a function'),
('What is a pointer in C?', 7, 'A variable that stores the address of another variable', 'A variable that stores the address of another variable', 'A variable that stores a value', 'A variable that points to a file', 'A variable that points to a function'),
('Which of the following is true about the "const" keyword in C?', 7, 'It makes a variable or function parameter constant', 'It makes a variable or function parameter constant', 'It defines a constant value', 'It creates a constant pointer', 'It prevents a function from being overridden'),
('What is the purpose of the "static" keyword in C?', 7, 'To declare a variable or function that is shared by all functions in a file', 'To declare a variable or function that is shared by all functions in a file', 'To create a static array', 'To prevent a variable from being modified', 'To define a global variable'),
('Which of the following is not a valid data type in C?', 7, 'string', 'string', 'int', 'char', 'float'),
('What is the purpose of a header file in C?', 7, 'To declare functions and macros to be shared between several source files', 'To declare functions and macros to be shared between several source files', 'To define global variables', 'To define the main() function', 'To include the source code of a program'),
('Which of the following is true about arrays in C?', 7, 'An array is a collection of elements of the same data type', 'An array is a collection of elements of the same data type', 'An array can store elements of different data types', 'The size of an array can be changed dynamically', 'An array can have elements of different sizes'),
('What is the output of the following C code?\n#include <stdio.h>\nint main() { char str[] = "Hello"; printf("%s", str); return 0; }', 7, 'Hello', 'Hello', 'Hello\n', 'Error', 'Undefined'),
('Which of the following is a correct syntax for defining a function in C?', 7, 'int func(int a) { return a; }', 'int func(int a) { return a; }', 'func int(int a) { return a; }', 'define func(int a) { return a; }', 'int func(int a); { return a; }'),
('What is a recursive function in C?', 7, 'A function that calls itself', 'A function that calls itself', 'A function that returns a pointer', 'A function that takes a pointer as an argument', 'A function that calls another function'),
('What is the difference between "break" and "continue" statements in C?', 7, 'The "break" statement terminates the loop, while the "continue" statement skips the current iteration and continues with the next iteration', 'The "break" statement terminates the loop, while the "continue" statement skips the current iteration and continues with the next iteration', 'The "continue" statement terminates the loop, while the "break" statement skips the current iteration', 'There is no difference', 'Both statements are used to terminate the loop'),
('Which of the following is true about a function pointer in C?', 7, 'It is a pointer that points to a function', 'It is a pointer that points to a function', 'It is a pointer that points to a variable', 'It is a function that returns a pointer', 'It is a function that takes a pointer as an argument');

INSERT INTO questions (question_text, category_id, correct_option, option1, option2, option3, option4) 
VALUES 
('What does OOP stand for?', 8, 'Object-Oriented Programming', 'Object-Oriented Programming', 'Object Oriented Procedure', 'Objective Operations Processing', 'Object-Oriented Procedure'),
('Which of the following is not an OOP concept?', 8, 'Compilation', 'Encapsulation', 'Compilation', 'Inheritance', 'Polymorphism'),
('Which feature of OOP provides the idea of reusability?', 8, 'Inheritance', 'Inheritance', 'Abstraction', 'Encapsulation', 'Polymorphism'),
('Which of the following is used to achieve runtime polymorphism?', 8, 'Method Overriding', 'Method Overloading', 'Method Overriding', 'Constructor Overloading', 'Function Overloading'),
('Which OOP concept is often compared to a blueprint?', 8, 'Class', 'Object', 'Function', 'Class', 'Inheritance'),
('Which term is used to describe the ability to take many forms in OOP?', 8, 'Polymorphism', 'Encapsulation', 'Polymorphism', 'Inheritance', 'Abstraction'),
('Which feature allows for hiding the internal implementation details?', 8, 'Encapsulation', 'Inheritance', 'Encapsulation', 'Polymorphism', 'Abstraction'),
('In OOP, what is used to bind data and functions together?', 8, 'Class', 'Object', 'Class', 'Method', 'Inheritance'),
('Which of the following is an example of an access specifier?', 8, 'private', 'void', 'int', 'public', 'private'),
('Which concept refers to the design of objects in classes?', 8, 'Encapsulation', 'Abstraction', 'Encapsulation', 'Polymorphism', 'Inheritance'),

('Which is the default access specifier in a class?', 8, 'private', 'public', 'private', 'protected', 'internal'),
('What is the process of defining multiple methods with the same name but different parameters?', 8, 'Overloading', 'Overloading', 'Overriding', 'Encapsulation', 'Inheritance'),
('What does the keyword `this` refer to in OOP?', 8, 'Current object', 'Super class', 'Parent class', 'Global variable', 'Current object'),
('Which OOP principle focuses on hiding the complexity of a system?', 8, 'Abstraction', 'Encapsulation', 'Polymorphism', 'Inheritance', 'Abstraction'),
('Which keyword is used to prevent a class from being inherited?', 8, 'final', 'static', 'final', 'abstract', 'protected'),
('Which method is called when an object is created?', 8, 'Constructor', 'Constructor', 'Destructor', 'Overloaded function', 'Static method'),
('What is the term for a function defined inside a class?', 8, 'Method', 'Procedure', 'Method', 'Constructor', 'Operator'),
('Which of the following allows objects to interact with each other?', 8, 'Methods', 'Constructors', 'Methods', 'Attributes', 'Events'),
('What is called when a child class provides a specific implementation of a method already defined in its parent class?', 8, 'Overriding', 'Overloading', 'Overriding', 'Abstracting', 'Encapsulation'),
('What OOP principle is demonstrated by the statement `a Circle is a Shape`?', 8, 'Inheritance', 'Polymorphism', 'Encapsulation', 'Inheritance', 'Abstraction'),

('Which OOP concept ensures that only the relevant details are shown to the user?', 8, 'Abstraction', 'Abstraction', 'Inheritance', 'Encapsulation', 'Polymorphism'),
('What is the relationship between a base class and a derived class?', 8, 'Inheritance', 'Composition', 'Aggregation', 'Inheritance', 'Polymorphism'),
('What type of relationship does composition represent?', 8, 'Has-a', 'Is-a', 'Has-a', 'Uses', 'Belongs-to'),
('Which of the following is not a type of inheritance?', 8, 'Sequential', 'Single', 'Multiple', 'Multilevel', 'Sequential'),
('What is it called when an object has multiple forms?', 8, 'Polymorphism', 'Encapsulation', 'Polymorphism', 'Inheritance', 'Abstraction'),
('Which OOP feature provides a way to perform a single action in different ways?', 8, 'Polymorphism', 'Inheritance', 'Polymorphism', 'Encapsulation', 'Abstraction'),
('Which keyword is used to inherit from a base class in Java?', 8, 'extends', 'implements', 'extends', 'inherits', 'derived'),
('What is the return type of a constructor in Java?', 8, 'No return type', 'void', 'int', 'double', 'No return type'),
('Which OOP concept focuses on separating an object’s interface from its implementation?', 8, 'Abstraction', 'Encapsulation', 'Inheritance', 'Polymorphism', 'Abstraction'),
('In OOP, what do you call a function that is called automatically when an object is destroyed?', 8, 'Destructor', 'Constructor', 'Destructor', 'Finalizer', 'Deinitializer'),

('Which method in a class must be implemented when an interface is used?', 8, 'All methods', 'Constructor', 'Destructor', 'All methods', 'Main method'),
('What does the `super` keyword refer to?', 8, 'Parent class', 'Current class', 'Child class', 'Global class', 'Parent class'),
('Which concept allows you to define a function in a child class that has the same name as one in the parent class?', 8, 'Overriding', 'Overloading', 'Encapsulation', 'Overriding', 'Inheritance'),
('Which of the following is not a benefit of using OOP?', 8, 'Faster execution', 'Code reusability', 'Data encapsulation', 'Faster execution', 'Modularity'),
('Which concept is related to controlling access to class members?', 8, 'Encapsulation', 'Inheritance', 'Abstraction', 'Encapsulation', 'Polymorphism'),
('Which keyword in C++ is used to inherit a class?', 8, 'public', 'public', 'private', 'protected', 'extends'),
('What is the primary purpose of encapsulation?', 8, 'To protect data', 'To protect data', 'To perform inheritance', 'To achieve polymorphism', 'To hide complexity'),
('In which phase of SDLC does object-oriented analysis take place?', 8, 'Analysis', 'Design', 'Analysis', 'Implementation', 'Testing'),
('Which method signature is correct for a destructor in C++?', 8, '~ClassName()', '~ClassName()', 'ClassName()', 'void ~ClassName()', 'ClassName~()'),
('Which is a real-world example of abstraction?', 8, 'Driving a car', 'Inheritance', 'Polymorphism', 'Driving a car', 'Method Overloading'),

('What is the output of `sizeof` operator in C++ when applied to an empty class?', 8, '8', '0', '4', '8', '8'),
('Which function is used to dynamically allocate memory in C++?', 8, 'new', 'malloc', 'calloc', 'new', 'realloc'),
('Which OOP concept is applied when creating an object from a class?', 8, 'Instantiation', 'Inheritance', 'Instantiation', 'Encapsulation', 'Abstraction'),
('Which of these is an example of method overloading?', 8, 'Same method name, different parameters', 'Different method names', 'Same method name, same parameters', 'Same method name, different parameters', 'Same return type'),
('Which keyword is used to make a member variable constant in C++?', 8, 'const', 'constant', 'const', 'final', 'static'),
('Which OOP concept allows for treating objects of different classes as objects of a common super class?', 8, 'Polymorphism', 'Encapsulation', 'Polymorphism', 'Inheritance', 'Abstraction'),
('What is the default visibility of class members in C++?', 8, 'private', 'public', 'protected', 'private', 'internal'),
('What type of inheritance does not exist in C++?', 8, 'Hybrid', 'Single', 'Multilevel', 'Multiple', 'Hybrid'),
('Which OOP principle is violated when a child class has more than one parent class?', 8, 'Single Inheritance', 'Multiple Inheritance', 'Single Inheritance', 'Polymorphism', 'Encapsulation'),
('Which keyword is used in Java to prevent a method from being overridden?', 8, 'final', 'static', 'final', 'private', 'protected'),

('In which language was the concept of OOP first introduced?', 8, 'Simula', 'Java', 'C++', 'Simula', 'Smalltalk'),
('What is it called when a class can extend another class?', 8, 'Inheritance', 'Encapsulation', 'Inheritance', 'Polymorphism', 'Abstraction'),
('Which of the following best describes an abstract class?', 8, 'A class that cannot be instantiated', 'A class that cannot be inherited', 'A class that cannot be instantiated', 'A class without methods', 'A class with private members only'),
('What does overriding a method in OOP allow you to do?', 8, 'Change the implementation of a method in a subclass', 'Create a method with the same name', 'Change the implementation of a method in a superclass', 'Change the implementation of a method in a subclass', 'Use multiple constructors'),
('Which of the following statements is true about constructors?', 8, 'Constructors can be overloaded', 'Constructors cannot have a return type', 'Constructors can be overloaded', 'Constructors are inherited', 'Constructors cannot accept parameters'),
('What is the output of calling a destructor in C++?', 8, 'Resource deallocation', 'Object creation', 'Function termination', 'Resource deallocation', 'Memory allocation'),
('Which of the following is a benefit of using interfaces in Java?', 8, 'Multiple inheritance', 'Multiple inheritance', 'Memory management', 'Encapsulation', 'Runtime polymorphism'),
('Which feature of OOP helps to hide the internal details of an object?', 8, 'Encapsulation', 'Inheritance', 'Encapsulation', 'Polymorphism', 'Abstraction'),
('What is the result of using the `delete` operator in C++?', 8, 'Deallocates memory', 'Creates an object', 'Initializes a variable', 'Deallocates memory', 'Releases a lock'),
('Which keyword is used in C++ to define a block of code as critical?', 8, 'lock', 'synchronized', 'lock', 'protected', 'critical');
